apiVersion : apps/v1
kind: Deployment
metadata:
  name: kafka1
  labels:
    app: kafka1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka1
  template:
    metadata:
      labels:
        app: kafka1
    spec:
      containers:
        - name: kafka1
          env:
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper:2181
          - name: KAFKA_ADVERTISED_LISTENERS 
            value: PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://kafka1:9092
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: 0.0.0.0
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          image: confluentinc/cp-kafka:5.3.0
---
apiVersion: v1
kind: Service
metadata:
    name: kafka1
spec:
    type: NodePort
    ports:
    - name: kafka1
      port: 9092
      targetPort: 9092
    selector:
        app: kafka1
